In [5]:
import re
import fitz  # PyMuPDF
import pandas as pd
import streamlit as st
import io

def extract_text_from_pdf(pdf_file):
    """Trích xuất toàn bộ text từ file PDF (file object từ Streamlit)."""
    text = ""
    with fitz.open(stream=pdf_file.read(), filetype="pdf") as pdf:
        for page in pdf:
            text += page.get_text("text")
    return text

# Mở file cục bộ
with open(r"E:\D\HOCDIBANTRE\AnhSa\20251019_SGN_CHNLASC0483158_JP_PARTA_1.pdf", "rb") as f:
    text = extract_text_from_pdf(f)

print(text[:1000000])  # In thử 1000 ký tự đầu

 Official External#
X:\1.DOCUMENTS\2.OUTBOUND\2.DAILY_CLP\06-OCT CNC
CHNL
FVNFSXX - CONTAINER LOADING PLAN / CFS OUTBOUND RECEIPT
Booking Number :
ASC0481452
Master file:
1069668951
CLP No.:
J5101701
Vessel Name :
PANAY - 3CGIEN1NC
CY cut off:
15H30 15-OCT-2025
POD:
TOKYO
Container number:
ECMU7438568
Tractor: 51C23089
ETD:
17/10/2025
Consignee:
JP
ETA:
26/10/2025
Seal number:
M3834934
Drop-off:
TRANSIMEX
Loading date:
6-Oct-25
Cont size:
40' High Cube Dry
Tranship port:
TOKYO
Time from:
To:
*ECMU7438568*
DOOR NO.
Trucker: SOLOG
No.
Inbound
Customs No.
Received Date
KN Reference
SP#
GTN S/O#
Shipper
Ship to Code
PO - LINE
CTN
 CBM
Gross Weight
Quantity
SWB
1
307569290620
7/14/2025
1067986598
A10G69668951
VB25070105417654
CHANG SHIN VIETNAM CO., LTD. 1084
3503814055 - 00050
20
1.090
120.38
97
ASC0481452
2
307598384020
7/26/2025
1068244406
A10G69668951
VB25071509238103
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503829934 - 00070
17
0.670
62.28
66
ASC0481452
3
307596143210
7/23/2025
1068270274
A10G69668951
VB25071601548568
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503814034 - 00050
23
1.450
127.75
108
ASC0481452
4
307651130200
8/9/2025
1068506920
A10G69668951
VB25072807448013
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842258 - 00040
34
2.340
264.64
198
ASC0481452
5
307660852240
8/14/2025
1068618125
A10G69668951
VB25080108252692
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503814030 - 00100
87
5.370
400.38
496
ASC0481452
6
307663806020
8/16/2025
1068669463
A10G69668951
VB25080117252898
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842232 - 00020
13
0.760
55.25
60
ASC0481452
7
307672226650
8/16/2025
1068665416
A10G69668951
VB25080118402904
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842256 - 00030
66
4.030
471.98
378
ASC0481452
8
307676201510
8/18/2025
1068673283
A10G69668951
VB25080418074897
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842255 - 00100
47
2.730
318.40
257
ASC0481452
9
307685124520
8/23/2025
1068736327
A10G69668951
VB25080509537029
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503829935 - 00030
28
1.290
120.05
127
ASC0481452
10
307685164420
8/23/2025
1068731820
A10G69668951
VB25080604237584
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842231 - 00020
16
0.750
51.71
67
ASC0481452
11
307685147510
8/23/2025
1068737383
A10G69668951
VB25080604537643
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842234 - 00040
15
0.750
45.87
61
ASC0481452
12
307687848220
8/21/2025
1068732419
A10G69668951
VB25080723098371
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842219 - 00050
17
0.870
60.91
72
ASC0481452
13
307687936310
8/21/2025
1068735849
A10G69668951
VB25080800548377
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842247 - 00060
14
0.520
40.91
71
ASC0481452
14
307719016160
8/30/2025
1068874899
A10G69668951
VB25081304522036
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503853284 - 00040
48
2.780
324.36
263
ASC0481452
15
307714051650
8/29/2025
1068923265
A10G69668951
VB25081605393710
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503853286 - 00040
33
2.030
219.07
163
ASC0481452
16
307766053140
9/18/2025
1069308428
A10G69668951
VB25083009372329
CHANG SHIN VIETNAM COMPANY LIMITED
1084
3503842238 - 00080
15
0.850
76.51
72
ASC0481452
17
307718949700
8/30/2025
1068867316
A10G69668951
VB25081211071595
CHANG SHIN VIETNAM COMPANY, LTD.
1084
3503842224 - 00060
75
4.700
403.81
444
ASC0481452
18
307614157710
7/28/2025
1068286365
13187084
VB25071803559697
DONA PACIFIC (VIETNAM) CO., LTD1084
3503813877 - 00030
16
0.800
89.00
85
ASC0483091
19
307636752750
8/6/2025
1068479756
13187085
VB25072507126050
FU-LUH SHOES CO., LTD
1084
3503842092 - 00030
48
3.070
236.00
263
ASC0483157
20
307637747010
8/6/2025
1068497526
13187086
VB25072607136389
POU CHEN VIETNAM ENTERPRISE LTD.
1084
3503842282 - 00090
31
0.730
52.49
68
ASC0483158
21
307637763110
8/6/2025
1068477642
13187086
VB25072802386805
POU CHEN VIETNAM ENTERPRISE LTD.
1084
3503842282 - 00100
27
0.690
49.11
64
ASC0483158
22
307691130960
8/23/2025
1068830556
13187086
VB25081302171738
POU CHEN VIETNAM ENTERPRISE LTD.
1084
3503830020 - 00020
38
0.850
78.53
100
ASC0483158
23
307596937560
7/23/2025
1068248087
13187087
VB25071509238111
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503811643 - 00020
15
0.810
64.96
74
ASC0483159
24
307661611630
8/13/2025
1068626688
13187087
VB25080403063739
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503814172 - 00110
21
1.040
82.70
91
ASC0483159
25
307682911450
8/20/2025
1068797795
13187087
VB25081109069826
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503814145 - 00070
26
1.260
135.64
106
ASC0483159
26
307682992060
8/20/2025
1068837573
13187087
VB25081207571254
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503814169 - 00040
21
1.040
78.45
89
ASC0483159
27
307683499450
8/20/2025
1068836954
13187087
VB25081207571345
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503842555 - 00020
22
1.180
85.30
99
ASC0483159
Container #
Carrier Seal #
Customs Seal #
ECMU7438568
M3834934
Page 1 of 3
 Official External#
28
307683156930
8/20/2025
1068838878
13187087
VB25081207571356
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503830816 - 00040
19
0.920
70.00
79
ASC0483159
29
307683830660
8/20/2025
1068820451
13187087
VB25081303371949
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503830806 - 00020
16
0.480
49.47
117
ASC0483159
30
307744806630
9/10/2025
1069164456
13187087
VB25082808261263
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503853553 - 00020
7
0.560
53.31
60
ASC0483159
31
307768051160
9/17/2025
1069391419
13187087
VB25090809025761
TKG TAEKWANG VINA JOINT STOCK COMPANY
1084
3503842565 - 00020
25
1.300
103.49
116
ASC0483159
32
307615439300
7/30/2025
1068289857
13187085
VB25071408337022
VIETNAM CHINGLUH SHOES CO., LTD
1084
3503829928 - 00040
21
1.520
116.00
84
ASC0483157
33
307657795010
8/13/2025
1068519514
13187085
VB25072902098853
VIETNAM CHINGLUH SHOES CO., LTD
1084
3503842095 - 00090
49
2.990
293.00
281
ASC0483157
34
307657676710
8/13/2025
1068519375
13187085
VB25072902098871
VIETNAM CHINGLUH SHOES CO., LTD
1084
3503842095 - 00100
49
2.950
289.00
278
ASC0483157
35
307657647420
8/13/2025
1068518997
13187085
VB25072902098874
VIETNAM CHINGLUH SHOES CO., LTD
1084
3503842077 - 00090
19
0.930
83.00
71
ASC0483157
36
307701657010
8/27/2025
1068838327
13187085
VB25081207571325
VIETNAM CHINGLUH SHOES CO., LTD
1084
3503853245 - 00040
30
1.800
214.00
174
ASC0483157
37
307660018910
8/12/2025
1068716373
13187088
VB25080610397973
VIETNAM DONA ORIENT CO., LTD1084
3503842270 - 00060
16
0.820
60.00
70
ASC0483160
38
307680715660
8/19/2025
1068863992
13187088
VB25081306372166
VIETNAM DONA ORIENT CO., LTD1084
3503842270 - 00050
16
0.820
60.00
70
ASC0483160
39
307629654160
8/1/2025
1068426167
13187090
VB25072312415461
Delta Galil Vietnam Co. Ltd
1084
3503835527 - 00040
4
0.250
22.54
114
ASC0483161
40
307685554100
8/20/2025
1068810359
13187091
VB25081108119748
E TOP VIET NAM CO.,LTD
1084
3503826191 - 00030
5
0.160
22.55
119
ASC0483162
41
307792439050
9/24/2025
1069519842
13187091
VB25091503388781
E TOP VIET NAM CO.,LTD
1084
3503823398 - 00270
5
0.160
22.55
119
ASC0483162
42
307691823520
8/22/2025
1068838673
13187091
VB25081206571086
ECLAT TEXTILE CO., LTD (VIETNAM).
1084
3503823382 - 00040
5
0.270
31.04
69
ASC0483162
43
307691832140
8/22/2025
1068838602
13187091
VB25081206571123
ECLAT TEXTILE CO., LTD (VIETNAM).
1084
3503826180 - 00030
5
0.090
12.75
69
ASC0483162
44
307790904210
9/24/2025
1069568705
13187094
VB25091608140325
FAR EASTERN APPAREL VIET NAM1084
3503817828 - 00010
9
0.610
59.84
124
ASC0483163
45
307779187130
9/24/2025
1069492279
13187095
VB25091207108127
HI-TECH VIET NAM APPAREL CO.,LTD.
1084
3503833498 - 00040
20
1.590
113.02
204
ASC0483164
46
307796586110
9/26/2025
1069506402
13187097
VB25091504238946
LUCKYTEX SOCTRANG VIETNAM CO.,LTD
1084
3503855161 - 00020
5
0.130
14.29
60
ASC0483165
47
307707174410
8/27/2025
1068866183
13187099
VB25081403532655
PRO KINGTEX VIETNAM CO., LTD 1084
3503817472 - 00040
8
0.300
74.33
129
ASC0483166
48
307745882160
9/10/2025
1069279490
13187099
VB25082907261709
PRO KINGTEX VIETNAM CO., LTD 1084
3503817475 - 00060
14
0.690
54.78
138
ASC0483166
49
307710064820
8/29/2025
1068958858
13187097
VB25081804104174
TUNTEX SOC TRANG VIETNAM CO., LTD
1084
3503834613 - 00080
7
0.300
32.30
77
ASC0483165
50
307683162050
8/20/2025
1068770190
13187103
VB25081102108979
WORLDON (VIETNAM) CO.,LTD
1084
3503818848 - 00050
10
0.780
98.30
156
ASC0483167
51
307731344230
9/5/2025
1069011778
13187103
VB25081605093686
WORLDON (VIETNAM) CO.,LTD
1084
3503855101 - 00010
28
1.940
202.17
303
ASC0483167
1225
66.810
6268.17
7120
2
Tare/ Mgw:
3700
32500
REMARK:
VGM:
9968.17
CONSIGNEE 1:
NIKE JAPAN GROUP LLC MIDTOWN TOWER 9-7-1 AKASAKA, MINATO-KU, TOKYO 107-6210, JAPAN PHONE: 81-3-4463-6453 / FAX:81-3-4463-6454
CONSIGNEE 2:
CONSIGNEE 3:
1. Prepared Docs:
3. Checked by Docs:
5. Trucking:
6. Security:
Remark:
Total
LẤY MẪU
2. Tallyman:
4. Seal:
1. Nhân viên chứng từ xác nhận đã chuẩn bị bộ chứng từ hàng xuất đầy đủ và chính xác/ ký xác nhận tại mục "1. Prepared Docs"
2. Tallyman xác nhận đã kiểm đếm và đóng hàng vào container đúng theo list đóng hàng/ ký xác nhận tại mục "2. Tallyman"
3. Nhân viên chứng từ xác nhận đã kiểm tra chứng từ đóng hàng, chứng từ hạ cont và bàn giao seal/ ký xác nhận tại mục "3. Checked by Docs"
4. Nhân viên seal xác nhận đã nhận seal, kiểm tra seal và bấm seal/ ký xác nhận tại mục "4. Seal"
5. Tài xế xác nhận đã nhận đầy đủ chứng từ kéo container hạ cảng/ ký xác nhận tại mục "5. Trucking"
6. Bảo vệ xác nhận đã bàn giao container và các chứng từ liên quan cho tài xế/ ký xác nhận tại mục "6. Security"
Tài xế xác nhận cont đã có đủ 2 seal
(Seal hãng tàu và seal hải quan)
Tài xế xác nhận cont đã có đủ 2 seal
(Seal hãng tàu và seal hải quan)
Page 2 of 3
 Official External#
Drop-off:
TRANSIMEX
1. PKL (2 TO) - MOC KN

4. VGM - MOC KN (2 TO)
¨
2. TO KHAI TRANG 3 (2 TO) - MOC KN

3. BOOKING TRANG 1

Page 3 of 3
Continued on Next Sheet
ECMU7438568             1 x 40HC  96 CARTONS                                              180.130     3700       2.270
SEAL M3834934
NO MARKS                          "31 CTN // 0.73 CBM // 52.49 KGS
                                  31 Cartons of Footwear Division of goods, Qty: 68
                                  PR
                                  Buy Group: FIRST QUALITY, AFS: 01000
                                  Ship-to Plant: 1084, Customer:
                                  Invoice#: PCVJ2509981
                                  PO-Item: 3503842282-90, Customer PO:
                                  Material: HV9981-200, Name: W NIKE FLEX TRAIN,
                                  Gender/Age: WOMENS
                                  Standard Description: WOMENS FITNESS/WORKOUT LOW
                                  TOP, HSCode: 640411
                                  Material Content: Textile (100%
                                  Polyester)/Synthetic Plastic
                                  **********************************
                                  27 CTN // 0.69 CBM // 49.11 KGS
                                  27 Cartons of Footwear Division of goods, Qty: 64
                                  PR
                                  Buy Group: FIRST QUALITY, AFS: 01000
                                  Ship-to Plant: 1084, Customer:
                                  Invoice#: PCVJ2509987
                                  PO-Item: 3503842282-100, Customer PO:
ASC0483158
of
KUEHNE + NAGEL CO., LTD.
TAX# 0312658789 ON BEHALF OF (*)
HO CHI MINH CITY, VIETNAM
LE THANH TON STREET, SAI GON WARD,
VINCOM CENTER BUILDING, NO.72
NIKE JAPAN GROUP LLC
JAPAN (**)
MINATO-KU, TOKYO 107-6210,
MIDTOWN TOWER, 9-7-1 AKASAKA,
(TAX ID: 1010703002010)
KINTETSU WORLD EXPRESS ,INC.
NO 3 1-7-17 SHIBA MINATO-KU
6F SUMITOMO FUDOSAN SHIBA BLDG
TOKYO SEA IMPORT CLEARANCE CENTER
(ON BEHALF OF NIKE JAPAN)
1
Sheet
HO CHI MINH CITY
TOKYO
HO CHI MINH CITY
  SHIPPER
  CONSIGNEE
  NOTIFY PARTY,  Carrier not to be responsible for failure to notify
PRE CARRIAGE BY*
  PLACE OF RECEIPT*
  FREIGHT TO BE PAID AT
VESSEL
  PORT OF LOADING
  FINAL PLACE OF DELIVERY*
  PORT OF DISCHARGE
MARKS AND NOS
CONTAINER AND SEALS
NO AND KIND
OF PACKAGES
DESCRIPTION OF PACKAGES AND GOODS AS STATED BY SHIPPER
GROSS WEIGHT
CARGO
MEASUREMENT
TARE
PLACE AND DATE OF ISSUE
SIGNED FOR THE SHIPPER
*APPLICABLE ONLY WHEN THIS DOCUMENT IS USED AS A COMBINED
TRANSPORT BILL OF LADING
VOYAGE NUMBER
ADDITIONAL CLAUSES
EXPORT REFERENCES
19 OCT 2025
ZERO (0)
TOKYO
SHIPPER'S LOAD  STOW AND COUNT    SAID TO CONTAIN
NON NEGOTIABLE
WAYBILL
WAYBILL NUMBER
TOKYO,105-0014, JAPAN >
NUMBER OF ORIGINAL WAYBILLS
KGS
KGS
CBM
as agents for the carrier CMA CGM Asia Shipping Pte. Ltd.
SIGNED FOR THE CARRIER CMA CGM Asia Shipping Pte. Ltd.
BY
_______________________________________________
CMA CGM VIETNAM JSC
Said to contain
This Waybill is governed by the Terms and Conditions available on the CNC website (www.cnc-line.com)
which the Merchant has read and accepted. The carrier is entitled to deliver the cargo to the Consignee,
after payment of any outstanding Freight, on provision of proper proof of identity without the need to
produce or surrender a copy of this Sea Waybill.
Shippers stow, load and count
Demurrage and detention payable by the Merchant as per the Carrier’s tariff available on the web site
www.cnc-line.com, or in any of his agency. However if special free time conditions are granted, then rates
applicable as per general tariff grid shall start from the day following the last free day.
For the purpose of the present carriage, clause 14(2) shall exclude the application of the York/Antwerp
rules, 2004
The shipper acknowledges that the Carrier is authorized to carry the goods identified in this bill of lading
on the deck of any vessel and in taking remittance of this bill of lading the Merchant (including the
shipper, the consignee and the holder of the bill of lading, as the case may be) confirms his express
acceptance of all the terms and conditions of this bill of lading and expressly confirms his unconditional
and irrevocable consent to the carriage of the goods on the deck of any vessel
Mis-declaration of cargo weight endangers crew, port workers and vessels' safety.  Your cargo may be
weighed at any place and time of carriage and any mis-declaration will expose you to claims for all losses,
expenses or damages whatsoever resulting thereof and be subject to freight surcharge
Following the exceptional measures adopted by various governments in relation with the outbreak of
COVID-19 virus and the operational constraints resulting thereof, the Merchants are hereby notified that
the carriage of cargo may be disrupted or delayed.Cargo may not be loaded on the intended vessel and
may be on forwarded to the port of destination on any alternative vessel at Carrier’s sole discretion.
Furthermore in case of disruption of ports’ operations, the cargo may be discharged in an alternative port
without notice and - subject to availability - be on forwarded to the original intended port of
destination.Carrier reserve its rights to accomplish the bill of lading in any alternative port. All additional
costs, including but not limited to storage, demurrage, plugging, monitoring  at the alternative discharge
port or extra on forwarding costs, shall be on Merchant's account and payable before delivery and the
carrier shall have no liability whatsoever for any loss or damage resulting thereof
PANAY
 Head Office: #15-01 The Metropolis, Tower 1
 9 North Buona Vista Drive, Singapore 138588
 Tel: (65) 6278 9000 -   Fax: (65) 6278 4900
CARRIER:
3CGIEN1NC
CMA CGM Asia Shipping Pte. Ltd.
RECEIVED by the Carrier from the Shipper in apparent good order and condition (unless otherwise noted herein) the total number or quantity of containers or other packages or units indicated above by the Merchant for carriage, subject to all the terms
hereof and tariff for the relevant trade, from the place of receipt or the port of loading, whichever applicable, to the port of discharge or place of delivery whichever applicable. This Waybill is deemed to be a contract of carriage as defined in Article I (b) of the
Hague Rules and Hague Visby Rules although this is not a document of title to the Goods.
DELIVERY will only be made on Payment of all Freight and Charges and to the named Consignee or any third party nominated by the Consignee by written instruction to the Carrier or his Agent, unless the Shipper instructs otherwise prior to delivery. The
rights and liabilities arising according to the terms hereof shall (without prejudice to any rule of common law and status) become binding between the Carrier and Consignee as if this agreement has been made between them and the Shipper guarantees on
reception of this Waybill that he has accepted it on his own behalf, on behalf of the Consignee and the Owner of the Goods, and warrants that he has authority to do so.
LAW AND JURISDICTION
i) Governing Law Insofar as anything has not been dealt with by the terms and conditions of this Bill of Lading, Singapore law shall apply. Singapore law shall in any event apply in interpreting the terms and conditions hereof.
ii) Jurisdiction All disputes relating to this Bill of Lading shall be determined by the Courts of Singapore to the exclusion of the jurisdiction of the courts of any other country provided always that the Carrier may in its absolute and sole discretion invoke or
voluntarily submit to the jurisdiction of the Courts of any other country which, but for the terms of this Bill of Lading, could properly assume jurisdiction to hear and determine such disputes, but shall not constitute a waiver of the terms of this provision in any
other instance.
iii) Notwithstanding i) and ii), if Carriage includes Carriage to, from or through a port in the United States of America, the Merchant may refer any claim or dispute to the United States District Court for the Southern District of New York in accordance with the
laws of the United States of America.
This Waybill is issued subject to the C.M.I Uniform Rules for Sea Waybills.
The contract evidenced by this Sea Waybill is subject to the terms, conditions, exceptions, limitations and liberties (including those relating to pre-carriage and on-carriage) set out in and incorporated by the Carrier’s Bill of Lading. The terms of the Carrier’s
Applicable Tariff are incorporated herein.
3
Total Quantity
INV#
PO#
PO Line#
style#
Continued From Previous Sheet
                                  Material: HV9981-600, Name: W NIKE FLEX TRAIN,
                                  Gender/Age: WOMENS
                                  Standard Description: WOMENS FITNESS/WORKOUT LOW
                                  TOP, HSCode: 640411
                                  Material Content: Textile (100%
                                  Polyester)/Synthetic Plastic
                                  **********************************
                                  38 CTN // 0.85 CBM // 78.53 KGS
                                  38 Cartons of Footwear Division of goods, Qty:
                                  100 PR
                                  Buy Group: FIRST QUALITY, AFS: 01000
                                  Ship-to Plant: 1084, Customer:
                                  Invoice#: PCVJ2508881
                                  PO-Item: 3503830020-20, Customer PO:
                                  Material: IM8053-237, Name: WMNS NIKE T90 SE,
                                  Gender/Age: WOMENS
                                  Standard Description: WOMENS SOCCER LOW TOP,
                                  HSCode: 640399
                                  Material Content: Full Grain Cow Leather/Textile
                                  (100% Polyester)/OUTSOLE: 100% Rubber
                                  **********************************
                                  (*)
                                  POU CHEN VIETNAM ENTERPRISE LTD.
                                  (**)
                                  Phone: 81-3-4463-6453 / Fax:81-3-4463-6454

In [32]:
import re
import pandas as pd

def find_text_after_keyword(text, keyword, num_chars=50):
    """
    Tìm đoạn văn bản sau một keyword. 
    Nếu cùng dòng không có nội dung, lấy nội dung ở dòng kế tiếp.
    """
    # 1️⃣ Tìm trên cùng dòng
    pattern_same_line = re.escape(keyword) + r"[ \t]*(.{1," + str(num_chars) + r"})"
    match = re.search(pattern_same_line, text)
    if match:
        result = match.group(1).strip()
        if result:
            return result

    # 2️⃣ Nếu không có, tìm ở dòng kế tiếp
    pattern_next_line = re.escape(keyword) + r"\s*\n\s*(.{1," + str(num_chars) + r"})"
    match = re.search(pattern_next_line, text)
    if match:
        return match.group(1).strip()

    return None


def split_by_bill_names(text, bill_names):
    """
    Tách text thành các phần tương ứng với bill_names (theo thứ tự trong danh sách).
    Mỗi bill_name chỉ xuất hiện 1 lần, lấy nội dung từ bill_i đến bill_(i+1).
    """
    sections = []
    text_lower = text.lower()
    
    # Dò vị trí xuất hiện của từng bill_name trong text
    positions = []
    for b in bill_names:
        idx = text_lower.find(b.lower())
        if idx != -1:
            positions.append((idx, b))
    
    # Sắp xếp theo vị trí xuất hiện
    # positions.sort()
    
    # Tách nội dung giữa các bill
    for i, (start_idx, bill) in enumerate(positions):
        end_idx = positions[i+1][0] if i + 1 < len(positions) else len(text)
        content = text[start_idx + len(bill): end_idx].strip()
        sections.append((bill, content))
        
        text = text[end_idx:].strip()
    return sections
def split_by_bill_names(text, bill_names):
    """
    Cắt text thành các phần tương ứng với bill_names.
    - Sau khi lấy một section, loại bỏ phần đó khỏi text.
    - Không cho phép 2 bill liên tiếp giống nhau.
    """
    sections = []
    text_lower = text.lower()
    pattern = "|".join([re.escape(b.lower()) for b in bill_names])

    prev_bill = None
    while True:
        match = re.search(pattern, text_lower)
        if not match:
            break  # không còn bill nào

        bill = next(b for b in bill_names if b.lower() == match.group(0))

        # Bỏ qua nếu trùng với bill trước
        if bill == prev_bill:
            # Cắt bỏ phần trùng rồi tiếp tục tìm tiếp
            text = text[match.end():].strip()
            text_lower = text.lower()
            continue

        # Tìm bill tiếp theo (để biết điểm kết thúc)
        next_match = re.search(pattern, text_lower[match.end():])
        end_idx = match.end() + next_match.start() if next_match else len(text)
        content = text[match.end():end_idx].strip()

        # Lưu lại section
        sections.append((bill, content))

        # Cắt bỏ phần đã xử lý khỏi text
        text = text[end_idx:].strip()
        text_lower = text.lower()
        prev_bill = bill

    return sections
def extract_bill_sections(text, bill_names, keyword_dict, verbose=False):
    """
    Extract info for each bill section based on grouped keywords.
    Each main key in keyword_dict will become a column name.
    """
    sections = split_by_bill_names(text, bill_names)
    results = []

    for bill_name, content in sections:
        if verbose:
            print(f"Processing section: {bill_name}")
            print(f"Snippet: {content}...")
            print("-" * 40)

        entry = {"Bill Name": bill_name}
        for key, kw_list in keyword_dict.items():
            if not kw_list:
                entry[key] = "⚠️ Not Found"
                continue
            vals = None
            for kw in kw_list:
                cont = find_text_after_keyword(content, kw)
                if cont is not None:
                    vals = cont
            if vals:
                entry[key] = vals
            else:
                entry[key] = "⚠️ Not Found"

        results.append(entry)

    return pd.DataFrame(results)


bill_names = [
    "WAYBILL",
    "Trading Company  Commercial Invoice",
    "Factory Commercial Invoice",
    "Factory Packing List ",
    "MULTIPLE COUNTRY OF ORIGIN DECLARATION",
    "Japan Customs Form",
        "WAYBILL",
    "Trading Company  Commercial Invoice",
    "Factory Commercial Invoice",
    "Factory Packing List ",
    "MULTIPLE COUNTRY OF ORIGIN DECLARATION",
    "Japan Customs Form",
        "WAYBILL",
    "Trading Company  Commercial Invoice",
    "Factory Commercial Invoice",
    "Factory Packing List ",
    "MULTIPLE COUNTRY OF ORIGIN DECLARATION",
    "Japan Customs Form",
            "WAYBILL",
    "Trading Company  Commercial Invoice",
    "Factory Commercial Invoice",
    "Factory Packing List ",
    "MULTIPLE COUNTRY OF ORIGIN DECLARATION",
    "Japan Customs Form",
]


keywords = {
    "INV": ["Invoice#:", "Invoice Number:", "Invoice Number.:", "INVOICE NO."],
    "Total weight": ["Total Gross Kgs:", "Total Gross Weight:"],
    "total volume": [],
    "PO": ["PO-Item:", "P.O.#:", "PO#:", "PO Number:", "Reference PO#:"],
    "PO line": ["ITEM:", "PO Line Item Seq.#:", "PO Line#:", "Item Seq.:", "Sizes:"],
    "Style": ["Material:", "Material No:", "Material#:", "MATERIAL", "Material #:"],
    "total carton": ["Amount", "Cartons:"],
    "total quantity": ["Total Quantity:", "Total Qty:", "Qty:", "Quantity:"]
}

df = extract_bill_sections(text, bill_names, keywords, verbose=True)
for i in range(len(df)):
    if "-" in str(df.loc[i, "PO"]):
        parts = df.loc[i, "PO"].split("-")
        df.loc[i, "PO"] = parts[0]
        df.loc[i, "PO line"] = parts[1] if len(parts) > 1 else None
    df["PO"] = df["PO"].astype(str).str.split(",").str[0]
    df["PO line"] = df["PO line"].astype(str).str.split(",").str[0]
    df["total quantity"] = df["total quantity"].astype(str).str.split(" ").str[0]
df

Processing section: WAYBILL
Snippet: ...
----------------------------------------
Processing section: Trading Company  Commercial Invoice
Snippet: SELLER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
SINGAPORE 117440
SINGAPORE
Company Registration Number: T16FC0027D
GST Registration Number: M90367331L
BUYER:
NIKE JAPAN GROUP LLC
9-7-1 AKASAKA
MIDTOWN TOWER
TOKYO 107-6210
MINATO-KU
JAPAN
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
ICHIKAWA 272-0001
JAPAN
Invoice Number:
4302168583
Invoice Date:
July 30, 2025
Reference Invoice #:
PCVJ2509981
SAP Factory Code:
VP
Terms of Sale:
FOB
Mode of  Transportation:
Vessel
Vessel/Airline:
Ship Date:
August 06, 2025
From:
Ho Chi Minh, Vietnam
To:
Tokyo, Tk Japan
Shipping Marks
Description of Goods
Size Range
Quantity
Unit Price
Amount
31 Cartons of Footwear Division Goods
PR
JPY
1084
To:
Tokyo, Tk Japan
Country of Origin:
Vietnam
Material#:
HV9981-200
Desc: W NIKE FLEX TRAIN
Material Content:
Textile (100%
Polyester)/Synthetic Plastic
Standard Description:
WOMENS
FITNESS/WORKOUT LOW TOP
Gender/Age:
WOMENS
Line:
WOMENS TRAINING
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
                                Plant:
1084
AFS Category: 01000
Buy Group:
FIRST QUALITY
PO#:
3503842282
Reference PO#:
8501935073
PO Line Item Seq.#:
00090
Sizes:
5-11
       68
3,201
217,668
--------------------------------------------------------------------------------------------------------------------------------------------------------
Total Number of
Cartons:
31
Total Invoice
Quantity:
68 Total Amount:
217,668
Total Gross Weight:
52.49 Kgs
Total Net Weight:
28.73 Kgs
Manufacturing Factory:
POU CHEN VIETNAM ENTERPRISE LTD.
Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province, Vietnam
Page 1 of    2
Printed on:
2025/08/04
19:41:25
INV#
Style#
PO#
PO line#
Total quantity
Total Weight
total carton...
----------------------------------------
Processing section: Factory Commercial Invoice
Snippet: Ho Chi Minh, Vietnam
Vessel
SELLER:
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan
BUYER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
Singapore  117440
SINGAPORE
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
Ichikawa, CH  272-0001
Japan
August 6, 2025
Ship Date:
Reference Invoice #:
Tokyo, Tk Japan
To:
4302168583
Shipping Marks
Description of Goods
Size
Range
Amount
Unit Price
Quantity
PR
USD
31
Cartons of Footwear Division Goods
HV9981-200
Material #:
Desc.:
W NIKE FLEX TRAIN
Material Content: Textile (100%
Polyester)/Synthetic Plastic
Standard Description: WOMENS
FITNESS/WORKOUT LOW TOP
Line:
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
Plant: 1084
AFS Category:
01000
Buy Group:
Country Of Origin:
Vietnam
WOMENS TRAINING
Gender/Age:
WOMENS
PO#:
FIRST QUALITY
8501935073
Sizes:
00090
PO Line Item Seq. #:
Reference PO#:
3503842282
Booking Number: VB25072607136389
1084
Tokyo, Tk Japan
5 - 11
 68
 18.67
 1,269.56
 68
Total Invoice Quantity:
Total Amount:
 1,269.56
Total Number of Cartons:
 31
 28.73
 52.49
Total Gross Weight:
Total Net Weight:
Kgs
Kgs
Page 1 of 2
Aug-5-2025
 2:29:37PM
Printed on:
INV#
Style#
PO#
PO line#
Total quantity
Total Weight
total carton
SELLER:
SHIP TO:
PCVJ2509981
July 30, 2025
Invoice Number:
Invoice Date:...
----------------------------------------
Processing section: Factory Packing List
Snippet: 1084
Date:
July 30, 2025
PO# :
Factory Code:
AFS Category:
Material:
Plant:
Item Seq.:
Customer Ship To: #:
Customer SO-Line #:
Customer PO #:
HV9981-200
1084
Purchase Doc Date:
MSR:
Total Gross Kgs:
Total CBM:
Total Cartons:
Total Units:
 31
 68
VP
01000
Invoice Number.:
20250521
HO2025
 0.73
00090
To:
Total Net Kgs:
 52.49
 28.73
Lot Numbers:
G2505B02127
No
Manufacturer ID:
009120196
Buy Group:
FIRST QUALITY
Tokyo, Tk Japan
PCVJ2509981
Reference PO#:
8501935073
3503842282
VB25072607136389
Booking Number:
Desc:
W NIKE FLEX TRAIN
Tokyo, Tk Japan
Vietnam
Country Of Origin:
From
To
Type
5
5.5
6
6.5
7
7.5
8
8.5
9
10
10.5
11
 Units
Cartons
Carton Range
Number of
Ctn.
Carton Contents -- Quantity by Size
4334956 4334957
 2
S1
2
 1
4334958 4334958
 1
S1
1
 1
4334959 4334959
 6
XM3
1
 6
4334961 4334961
 6
XM3
1
 6
4334963 4334964
 12
XM3
2
 6
4334966 4334967
 12
XM3
2
 6
4334968 4334968
 6
XM3
1
 6
4334969 4334969
 1
S1
1
 1
4334970 4334972
 3
S1
3
 1
4334973 4334973
 1
S2
1
 1
4334974 4334974
 1
S2
1
 1
4334975 4334975
 2
S3
1
 2
Page 1 of 2
 2:29:38PM
Aug -5-2025
Printed on:
total weight
INV#
PO#
PO line#
Style#
seller:
(Continued)
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan...
----------------------------------------
Processing section: MULTIPLE COUNTRY OF ORIGIN DECLARATION
Snippet: We are  POU CHEN VIETNAM ENTERPRISE LTD - declare that the articles described below and coverd by the invoice or entry to which declaration relates were exported from the country
" identified below on the dates listed and were subjected to assembling , manufacturing or processing operations in , and/or incorporate materials originating in the
foreign territory of country", or the U.S. or an insular prossession of the U.S. identified below . I declare that the information set forth in this declaration is correct
and true to the best of my information , knowledge, and belidf .
A __TAIWAN--------------__(Country")
C_KOREA_____________________________(Country")
B __VIETNAM___(Country")
D__________________________________(Country")
Description of
Description of country of manufacturing
Materials
article and quantity
manufacturing
and or processing
and or processing
operations
Country
Date of
Description
Country
Date of
exportation
of materials
of origin
exportation

INVOICE NO.
PCVJ2509981
Making
B
08/06/25
A
06/07/25
31 CNTS OF NIKE FOOTWEAR GOODS
cutting
CAT
sewing
MATERIAL
HV9981-200
ITEM : 90
lasting
DESC.



GENDER
WOMENS
MATERIAL CONTENT 34% Plastic & 66% Textile
PURCHASE DOC DATE 20250521
SHIP TO ID#
PLANT
1084
AFS CATEGORY
01000
P.O. #:
3503842282
BUY GROUP
01
DATE  :
08/02/2025
NAME :
SIGNATURE :
TITLE : DIRECTOR
COMPANY: POU CHEN VIETNAM ENTERPRISE LTD
ADDRESS : Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province,  Vietnam
Country when used in this declaration includes territories and U.S. insular possessions the country will be indentified in the above declaration by the alphabetical
designation appearing next to the named country .
COUNTRY OF ORIGIN: VIET
NAM
Marks of
identification
34% Plastic & 66%
Textile
W NIKE FLEX TRAIN
TOKYO, TK Japan
1084

INV#
Style#
PO line#
PO#...
----------------------------------------
Processing section: Trading Company  Commercial Invoice
Snippet: SELLER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
SINGAPORE 117440
SINGAPORE
Company Registration Number: T16FC0027D
GST Registration Number: M90367331L
BUYER:
NIKE JAPAN GROUP LLC
9-7-1 AKASAKA
MIDTOWN TOWER
TOKYO 107-6210
MINATO-KU
JAPAN
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
ICHIKAWA 272-0001
JAPAN
Invoice Number:
4302168585
Invoice Date:
July 30, 2025
Reference Invoice #:
PCVJ2509987
SAP Factory Code:
VP
Terms of Sale:
FOB
Mode of  Transportation:
Vessel
Vessel/Airline:
Ship Date:
August 06, 2025
From:
Ho Chi Minh, Vietnam
To:
Tokyo, Tk Japan
Shipping Marks
Description of Goods
Size Range
Quantity
Unit Price
Amount
27 Cartons of Footwear Division Goods
PR
JPY
1084
To:
Tokyo, Tk Japan
Country of Origin:
Vietnam
Material#:
HV9981-600
Desc: W NIKE FLEX TRAIN
Material Content:
Textile (100%
Polyester)/Synthetic Plastic
Standard Description:
WOMENS
FITNESS/WORKOUT LOW TOP
Gender/Age:
WOMENS
Line:
WOMENS TRAINING
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
                                Plant:
1084
AFS Category: 01000
Buy Group:
FIRST QUALITY
PO#:
3503842282
Reference PO#:
8501935073
PO Line Item Seq.#:
00100
Sizes:
5-11
       64
3,189
204,096
--------------------------------------------------------------------------------------------------------------------------------------------------------
Total Number of
Cartons:
27
Total Invoice
Quantity:
64 Total Amount:
204,096
Total Gross Weight:
49.11 Kgs
Total Net Weight:
26.99 Kgs
Manufacturing Factory:
POU CHEN VIETNAM ENTERPRISE LTD.
Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province, Vietnam
Page 1 of    2
Printed on:
2025/08/04
19:45:56...
----------------------------------------
Processing section: Factory Commercial Invoice
Snippet: Ho Chi Minh, Vietnam
Vessel
SELLER:
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan
BUYER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
Singapore  117440
SINGAPORE
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
Ichikawa, CH  272-0001
Japan
August 6, 2025
Ship Date:
Reference Invoice #:
Tokyo, Tk Japan
To:
4302168585
Shipping Marks
Description of Goods
Size
Range
Amount
Unit Price
Quantity
PR
USD
27
Cartons of Footwear Division Goods
HV9981-600
Material #:
Desc.:
W NIKE FLEX TRAIN
Material Content: Textile (100%
Polyester)/Synthetic Plastic
Standard Description: WOMENS
FITNESS/WORKOUT LOW TOP
Line:
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
Plant: 1084
AFS Category:
01000
Buy Group:
Country Of Origin:
Vietnam
WOMENS TRAINING
Gender/Age:
WOMENS
PO#:
FIRST QUALITY
8501935073
Sizes:
00100
PO Line Item Seq. #:
Reference PO#:
3503842282
Booking Number: VB25072802386805
1084
Tokyo, Tk Japan
5 - 11
 64
 18.60
 1,190.40
 64
Total Invoice Quantity:
Total Amount:
 1,190.40
Total Number of Cartons:
 27
 26.99
 49.11
Total Gross Weight:
Total Net Weight:
Kgs
Kgs
Page 1 of 2
Aug-5-2025
 2:30:41PM
Printed on:
SELLER:
SHIP TO:
PCVJ2509987
July 30, 2025
Invoice Number:
Invoice Date:...
----------------------------------------
Processing section: Factory Packing List
Snippet: 1084
Date:
July 30, 2025
PO# :
Factory Code:
AFS Category:
Material:
Plant:
Item Seq.:
Customer Ship To: #:
Customer SO-Line #:
Customer PO #:
HV9981-600
1084
Purchase Doc Date:
MSR:
Total Gross Kgs:
Total CBM:
Total Cartons:
Total Units:
 27
 64
VP
01000
Invoice Number.:
20250521
HO2025
 0.69
00100
To:
Total Net Kgs:
 49.11
 26.99
Lot Numbers:
G2505B02223
No
Manufacturer ID:
009120196
Buy Group:
FIRST QUALITY
Tokyo, Tk Japan
PCVJ2509987
Reference PO#:
8501935073
3503842282
VB25072802386805
Booking Number:
Desc:
W NIKE FLEX TRAIN
Tokyo, Tk Japan
Vietnam
Country Of Origin:
From
To
Type
5
5.5
6
6.5
7
7.5
8
8.5
9
10
10.5
11
 Units
Cartons
Carton Range
Number of
Ctn.
Carton Contents -- Quantity by Size
4348158 4348159
 2
S1
2
 1
4348160 4348160
 1
S1
1
 1
4348161 4348161
 6
XM3
1
 6
4348162 4348162
 1
S1
1
 1
4348163 4348164
 12
XM3
2
 6
4348166 4348167
 12
XM3
2
 6
4348169 4348169
 6
XM3
1
 6
4348171 4348171
 6
XM3
1
 6
4348172 4348172
 1
S1
1
 1
4348173 4348175
 3
S1
3
 1
4348176 4348176
 1
S2
1
 1
4348177 4348177
 1
S2
1
 1
Page 1 of 2
 2:30:44PM
Aug -5-2025
Printed on:
seller:
(Continued)
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan...
----------------------------------------
Processing section: MULTIPLE COUNTRY OF ORIGIN DECLARATION
Snippet: We are  POU CHEN VIETNAM ENTERPRISE LTD - declare that the articles described below and coverd by the invoice or entry to which declaration relates were exported from the country
" identified below on the dates listed and were subjected to assembling , manufacturing or processing operations in , and/or incorporate materials originating in the
foreign territory of country", or the U.S. or an insular prossession of the U.S. identified below . I declare that the information set forth in this declaration is correct
and true to the best of my information , knowledge, and belidf .
A __TAIWAN--------------__(Country")
C_KOREA_____________________________(Country")
B __VIETNAM___(Country")
D__________________________________(Country")
Description of
Description of country of manufacturing
Materials
article and quantity
manufacturing
and or processing
and or processing
operations
Country
Date of
Description
Country
Date of
exportation
of materials
of origin
exportation

INVOICE NO.
PCVJ2509987
Making
B
08/06/25
A
06/07/25
27 CNTS OF NIKE FOOTWEAR GOODS
cutting
CAT
sewing
MATERIAL
HV9981-600
ITEM : 100
lasting
DESC.



GENDER
WOMENS
MATERIAL CONTENT 34% Plastic & 66% Textile
PURCHASE DOC DATE 20250521
SHIP TO ID#
PLANT
1084
AFS CATEGORY
01000
P.O. #:
3503842282
BUY GROUP
01
DATE  :
08/02/2025
NAME :
SIGNATURE :
TITLE : DIRECTOR
COMPANY: POU CHEN VIETNAM ENTERPRISE LTD
ADDRESS : Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province,  Vietnam
Country when used in this declaration includes territories and U.S. insular possessions the country will be indentified in the above declaration by the alphabetical
designation appearing next to the named country .
COUNTRY OF ORIGIN: VIET
NAM
Marks of
identification
34% Plastic & 66%
Textile
W NIKE FLEX TRAIN
TOKYO, TK Japan
1084...
----------------------------------------
Processing section: Trading Company  Commercial Invoice
Snippet: SELLER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
SINGAPORE 117440
SINGAPORE
Company Registration Number: T16FC0027D
GST Registration Number: M90367331L
BUYER:
NIKE JAPAN GROUP LLC
9-7-1 AKASAKA
MIDTOWN TOWER
TOKYO 107-6210
MINATO-KU
JAPAN
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
ICHIKAWA 272-0001
JAPAN
Invoice Number:
4302180885
Invoice Date:
August 16, 2025
Reference Invoice #:
PCVJ2508881
SAP Factory Code:
VP
Terms of Sale:
FOB
Mode of  Transportation:
Vessel
Vessel/Airline:
Ship Date:
August 23, 2025
From:
Ho Chi Minh, Vietnam
To:
Tokyo, Tk Japan
Shipping Marks
Description of Goods
Size Range
Quantity
Unit Price
Amount
38 Cartons of Footwear Division Goods
PR
JPY
1084
To:
Tokyo, Tk Japan
Country of Origin:
Vietnam
Material#:
IM8053-237
Desc: WMNS NIKE T90 SE
Material Content:
Full Grain Cow Leather/Textile
(100% Polyester)/OUTSOLE: 100% Rubber
Standard Description:
WOMENS SOCCER LOW
TOP
Gender/Age:
WOMENS
Line:
NSW SOCCER
Purchase Doc Date:
20250507
HO2025
Ship To ID#:
                                Plant:
1084
AFS Category: 01000
Buy Group:
FIRST QUALITY
PO#:
3503830020
Reference PO#:
8501925841
PO Line Item Seq.#:
00020
Sizes:
5-12
      100
4,637
463,700
--------------------------------------------------------------------------------------------------------------------------------------------------------
Total Number of
Cartons:
38
Total Invoice
Quantity:
100 Total Amount:
463,700
Total Gross Weight:
78.53 Kgs
Total Net Weight:
51.12 Kgs
Manufacturing Factory:
POU CHEN VIETNAM ENTERPRISE LTD.
Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province, Vietnam
Page 1 of    2
Printed on:
2025/08/21
19:16:27...
----------------------------------------
Processing section: Factory Commercial Invoice
Snippet: Ho Chi Minh, Vietnam
Vessel
SELLER:
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan
BUYER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
Singapore  117440
SINGAPORE
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
Ichikawa, CH  272-0001
Japan
August 23, 2025
Ship Date:
Reference Invoice #:
Tokyo, Tk Japan
To:
4302180885
Shipping Marks
Description of Goods
Size
Range
Amount
Unit Price
Quantity
PR
USD
38
Cartons of Footwear Division Goods
IM8053-237
Material #:
Desc.:
WMNS NIKE T90 SE
Material Content: Full Grain Cow Leather/Textile
(100% Polyester)/OUTSOLE: 100% Rubber
Standard Description: WOMENS SOCCER LOW
TOP
Line:
Purchase Doc Date:
20250507
HO2025
Ship To ID#:
Plant: 1084
AFS Category:
01000
Buy Group:
Country Of Origin:
Vietnam
NSW SOCCER
Gender/Age:
WOMENS
PO#:
FIRST QUALITY
8501925841
Sizes:
00020
PO Line Item Seq. #:
Reference PO#:
3503830020
Booking Number: VB25081302171738
1084
Tokyo, Tk Japan
5 - 12
 100
 27.02
 2,702.00
 100
Total Invoice Quantity:
Total Amount:
 2,702.00
Total Number of Cartons:
 38
 51.12
 78.53
Total Gross Weight:
Total Net Weight:
Kgs
Kgs
Page 1 of 2
Aug-22-2025
 2:47:40PM
Printed on:
SELLER:
SHIP TO:
PCVJ2508881
August 16, 2025
Invoice Number:
Invoice Date:...
----------------------------------------
Processing section: Factory Packing List
Snippet: 1084
Date:
August 16, 2025
PO# :
Factory Code:
AFS Category:
Material:
Plant:
Item Seq.:
Customer Ship To: #:
Customer SO-Line #:
Customer PO #:
IM8053-237
1084
Purchase Doc Date:
MSR:
Total Gross Kgs:
Total CBM:
Total Cartons:
Total Units:
 38
 100
VP
01000
Invoice Number.:
20250507
HO2025
 0.85
00020
To:
Total Net Kgs:
 78.53
 51.12
Lot Numbers:
G2505A05410
No
Manufacturer ID:
009120196
Buy Group:
FIRST QUALITY
Tokyo, Tk Japan
PCVJ2508881
Reference PO#:
8501925841
3503830020
VB25081302171738
Booking Number:
Desc:
WMNS NIKE T90 SE
Tokyo, Tk Japan
Vietnam
Country Of Origin:
From
To
Type
5
5.5
6
6.5
7
7.5
8
8.5
9
9.5
10
10.5
11
11.5
12
 Units
Cartons
Carton Range
Number of
Ctn.
Carton Contents -- Quantity by Size
4412837 4412837
 4
S3
1
 4
4412838 4412838
 5
S4
1
 5
4412839 4412839
 6
XM2
1
 6
4412840 4412840
 1
S1
1
 1
4412841 4412842
 12
XM2
2
 6
4412844 4412845
 12
XM2
2
 6
4412846 4412846
 5
S4
1
 5
4412847 4412847
 6
XM2
1
 6
4412848 4412848
 4
S3
1
 4
4412849 4412849
 6
XM2
1
 6
4412850 4412850
 4
S3
1
 4
4412851 4412851
 6
XM2
1
 6
Page 1 of 2
 2:47:41PM
Aug -22-2025
Printed on:
seller:
(Continued)
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan...
----------------------------------------
Processing section: MULTIPLE COUNTRY OF ORIGIN DECLARATION
Snippet: We are  POU CHEN VIETNAM ENTERPRISE LTD - declare that the articles described below and coverd by the invoice or entry to which declaration relates were exported from the country
" identified below on the dates listed and were subjected to assembling , manufacturing or processing operations in , and/or incorporate materials originating in the
foreign territory of country", or the U.S. or an insular prossession of the U.S. identified below . I declare that the information set forth in this declaration is correct
and true to the best of my information , knowledge, and belidf .
A __TAIWAN--------------__(Country")
C_KOREA_____________________________(Country")
B __VIETNAM___(Country")
D__________________________________(Country")
Description of
Description of country of manufacturing
Materials
article and quantity
manufacturing
and or processing
and or processing
operations
Country
Date of
Description
Country
Date of
exportation
of materials
of origin
exportation

INVOICE NO.
PCVJ2508881
Making
B
08/23/25
A
06/24/25
38 CNTS OF NIKE FOOTWEAR GOODS
cutting
CAT
sewing
MATERIAL
IM8053-237
ITEM : 20
lasting
DESC.



GENDER
WOMENS
MATERIAL CONTENT 98% Plastic & 2% Textile
PURCHASE DOC DATE 20250507
SHIP TO ID#
PLANT
1084
AFS CATEGORY
01000
P.O. #:
3503830020
BUY GROUP
01
DATE  :
08/14/2025
NAME :
SIGNATURE :
TITLE : DIRECTOR
COMPANY: POU CHEN VIETNAM ENTERPRISE LTD
ADDRESS : Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province,  Vietnam
Country when used in this declaration includes territories and U.S. insular possessions the country will be indentified in the above declaration by the alphabetical
designation appearing next to the named country .
COUNTRY OF ORIGIN: VIET
NAM
Marks of
identification
98% Plastic & 2%
Textile
WMNS NIKE T90 SE
TOKYO, TK JAPAN

,Bill Name,INV,Total weight,total volume,PO,PO line,Style,total carton,total quantity
0,WAYBILL,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️
1,Trading Company Commercial Invoice,4302168583,52.49 Kgs,⚠️ Not Found,8501935073,5-11,HV9981-200,31,68
2,Factory Commercial Invoice,Invoice Date:,Total Net Weight:,⚠️ Not Found,3503842282,00090,Desc.:,31,Total
3,Factory Packing List,20250521,Total CBM:,⚠️ Not Found,8501935073,Customer Ship To: #:,Plant:,Total Units:,⚠️
4,MULTIPLE COUNTRY OF ORIGIN DECLARATION,PCVJ2509981,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,CONTENT 34% Plastic & 66% Textile,⚠️ Not Found,⚠️
5,Trading Company Commercial Invoice,4302168585,49.11 Kgs,⚠️ Not Found,8501935073,5-11,HV9981-600,27,64
6,Factory Commercial Invoice,Invoice Date:,Total Net Weight:,⚠️ Not Found,3503842282,00100,Desc.:,27,Total
7,Factory Packing List,20250521,Total CBM:,⚠️ Not Found,8501935073,Customer Ship To: #:,Plant:,Total Units:,⚠️
8,MULTIPLE COUNTRY OF ORIGIN DECLARATION,PCVJ2509987,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,CONTENT 34% Plastic & 66% Textile,⚠️ Not Found,⚠️
9,Trading Company Commercial Invoice,4302180885,78.53 Kgs,⚠️ Not Found,8501925841,5-12,IM8053-237,38,100
10,Factory Commercial Invoice,Invoice Date:,Total Net Weight:,⚠️ Not Found,3503830020,00020,Desc.:,38,Total
11,Factory Packing List,20250507,Total CBM:,⚠️ Not Found,8501925841,Customer Ship To: #:,Plant:,Total Units:,⚠️
12,MULTIPLE COUNTRY OF ORIGIN DECLARATION,PCVJ2508881,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,CONTENT 98% Plastic & 2% Textile,⚠️ Not Found,⚠️

In [7]:
keywords = {
    "INV": ["Invoice#:", "Invoice Number:", "Invoice Number.:", "INVOICE NO."],
    "Total weight": ["Total Gross Kgs:"],
    "total volume": [],
    "PO": ["PO-Item:", "P.O.#:", "PO#:", "PO Number:"],
    "PO line": ["ITEM:", "PO Line No:", "PO Line#:"],
    "Style": ["Material:", "Material No:", "Material#:", "MATERIAL"],
    "total carton": ["Total Carton:", "Total Cartons:", "Total No. of Cartons:"],
    "total quantity": ["Total Quantity:", "Total Qty:", "Qty:"]
}

In [8]:
def find_text_after_keyword(text, keyword, num_chars=50):
    """
    Tìm đoạn văn bản sau một keyword. 
    Nếu cùng dòng không có nội dung, lấy nội dung ở dòng kế tiếp.
    """
    # 1️⃣ Tìm trên cùng dòng
    pattern_same_line = re.escape(keyword) + r"[ \t]*(.{1," + str(num_chars) + r"})"
    match = re.search(pattern_same_line, text)
    if match:
        result = match.group(1).strip()
        if result:
            return result

    # 2️⃣ Nếu không có, tìm ở dòng kế tiếp
    pattern_next_line = re.escape(keyword) + r"\s*\n\s*(.{1," + str(num_chars) + r"})"
    match = re.search(pattern_next_line, text)
    if match:
        return match.group(1).strip()

    return None

def split_by_bill_names(text, bill_names):
    """
    Tách text thành các phần tương ứng với bill_names (theo thứ tự trong danh sách).
    Mỗi bill_name chỉ xuất hiện 1 lần, lấy nội dung từ bill_i đến bill_(i+1).
    """
    sections = []
    text_lower = text.lower()
    
    # Dò vị trí xuất hiện của từng bill_name trong text
    positions = []
    for b in bill_names:
        idx = text_lower.find(b.lower())
        if idx != -1:
            positions.append((idx, b))
    
    # Sắp xếp theo vị trí xuất hiện
    positions.sort()
    
    # Tách nội dung giữa các bill
    for i, (start_idx, bill) in enumerate(positions):
        end_idx = positions[i+1][0] if i + 1 < len(positions) else len(text)
        content = text[start_idx + len(bill): end_idx].strip()
        sections.append((bill, content))
    
    return sections


def extract_bill_sections(text, bill_names, keywords):
    sections = split_by_bill_names(text, bill_names)
    results = []

    for bill_name, content in sections:
        print(f"Processing section: {bill_name}")
        print(f"Content snippet: {content}...")  # In thử 100 ký tự đầu của nội dung
        print("-" * 40)
        entry = {"Bill Name": bill_name}
        for kw in keywords:
            result = find_text_after_keyword(content, kw)
            entry[kw] = result if result else "⚠️ Not Found"
        results.append(entry)
    return pd.DataFrame(results)


bill_names = ["WAYBILL", "Trading Company  Commercial Invoice", "Factory Commercial Invoice", "Factory Packing List ", "MULTIPLE COUNTRY OF ORIGIN DECLARATION", "Japan Customs Form"]
    
keywords = [
    "Invoice#:",
    "PO-Item:",
    "Material:",
    "NO MARKS",
    "Reference Invoice #:",
    "Material#:",
    "Material #:",
    "Invoice Number:",
    "Total Gross Weight:",
    "Reference PO#:",
    "Total Number of Cartons: ",
    "Total Invoice Quantity:",
    "PO Line Item Seq. #:",
    "Invoice Number.:",
    "Material:",
    "Reference PO#:",
    '''INVOICE NO. 
    :''',
    "STYLE/CLR:"
    
]

df = extract_bill_sections(text, bill_names, keywords)

Processing section: WAYBILL
Content snippet: WAYBILL NUMBER
TOKYO,105-0014, JAPAN >
NUMBER OF ORIGINAL WAYBILLS
KGS
KGS
CBM
as agents for the carrier CMA CGM Asia Shipping Pte. Ltd.
SIGNED FOR THE CARRIER CMA CGM Asia Shipping Pte. Ltd.
BY
_______________________________________________
CMA CGM VIETNAM JSC
Said to contain
This Waybill is governed by the Terms and Conditions available on the CNC website (www.cnc-line.com)
which the Merchant has read and accepted. The carrier is entitled to deliver the cargo to the Consignee,
after payment of any outstanding Freight, on provision of proper proof of identity without the need to
produce or surrender a copy of this Sea Waybill.
Shippers stow, load and count
Demurrage and detention payable by the Merchant as per the Carrier’s tariff available on the web site
www.cnc-line.com, or in any of his agency. However if special free time conditions are granted, then rates
applicable as per general tariff grid shall start from the day following the last free day.
For the purpose of the present carriage, clause 14(2) shall exclude the application of the York/Antwerp
rules, 2004
The shipper acknowledges that the Carrier is authorized to carry the goods identified in this bill of lading
on the deck of any vessel and in taking remittance of this bill of lading the Merchant (including the
shipper, the consignee and the holder of the bill of lading, as the case may be) confirms his express
acceptance of all the terms and conditions of this bill of lading and expressly confirms his unconditional
and irrevocable consent to the carriage of the goods on the deck of any vessel
Mis-declaration of cargo weight endangers crew, port workers and vessels' safety.  Your cargo may be
weighed at any place and time of carriage and any mis-declaration will expose you to claims for all losses,
expenses or damages whatsoever resulting thereof and be subject to freight surcharge
Following the exceptional measures adopted by various governments in relation with the outbreak of
COVID-19 virus and the operational constraints resulting thereof, the Merchants are hereby notified that
the carriage of cargo may be disrupted or delayed.Cargo may not be loaded on the intended vessel and
may be on forwarded to the port of destination on any alternative vessel at Carrier’s sole discretion.
Furthermore in case of disruption of ports’ operations, the cargo may be discharged in an alternative port
without notice and - subject to availability - be on forwarded to the original intended port of
destination.Carrier reserve its rights to accomplish the bill of lading in any alternative port. All additional
costs, including but not limited to storage, demurrage, plugging, monitoring  at the alternative discharge
port or extra on forwarding costs, shall be on Merchant's account and payable before delivery and the
carrier shall have no liability whatsoever for any loss or damage resulting thereof
PANAY
 Head Office: #15-01 The Metropolis, Tower 1
 9 North Buona Vista Drive, Singapore 138588
 Tel: (65) 6278 9000 -   Fax: (65) 6278 4900
CARRIER:
3CGIEN1NC
CMA CGM Asia Shipping Pte. Ltd.
RECEIVED by the Carrier from the Shipper in apparent good order and condition (unless otherwise noted herein) the total number or quantity of containers or other packages or units indicated above by the Merchant for carriage, subject to all the terms
hereof and tariff for the relevant trade, from the place of receipt or the port of loading, whichever applicable, to the port of discharge or place of delivery whichever applicable. This Waybill is deemed to be a contract of carriage as defined in Article I (b) of the
Hague Rules and Hague Visby Rules although this is not a document of title to the Goods.
DELIVERY will only be made on Payment of all Freight and Charges and to the named Consignee or any third party nominated by the Consignee by written instruction to the Carrier or his Agent, unless the Shipper instructs otherwise prior to delivery. The
rights and liabilities arising according to the terms hereof shall (without prejudice to any rule of common law and status) become binding between the Carrier and Consignee as if this agreement has been made between them and the Shipper guarantees on
reception of this Waybill that he has accepted it on his own behalf, on behalf of the Consignee and the Owner of the Goods, and warrants that he has authority to do so.
LAW AND JURISDICTION
i) Governing Law Insofar as anything has not been dealt with by the terms and conditions of this Bill of Lading, Singapore law shall apply. Singapore law shall in any event apply in interpreting the terms and conditions hereof.
ii) Jurisdiction All disputes relating to this Bill of Lading shall be determined by the Courts of Singapore to the exclusion of the jurisdiction of the courts of any other country provided always that the Carrier may in its absolute and sole discretion invoke or
voluntarily submit to the jurisdiction of the Courts of any other country which, but for the terms of this Bill of Lading, could properly assume jurisdiction to hear and determine such disputes, but shall not constitute a waiver of the terms of this provision in any
other instance.
iii) Notwithstanding i) and ii), if Carriage includes Carriage to, from or through a port in the United States of America, the Merchant may refer any claim or dispute to the United States District Court for the Southern District of New York in accordance with the
laws of the United States of America.
This Waybill is issued subject to the C.M.I Uniform Rules for Sea Waybills.
The contract evidenced by this Sea Waybill is subject to the terms, conditions, exceptions, limitations and liberties (including those relating to pre-carriage and on-carriage) set out in and incorporated by the Carrier’s Bill of Lading. The terms of the Carrier’s
Applicable Tariff are incorporated herein.
3
Total Quantity
INV#
PO#
PO Line#
style#
Continued From Previous Sheet
                                  Material: HV9981-600, Name: W NIKE FLEX TRAIN,
                                  Gender/Age: WOMENS
                                  Standard Description: WOMENS FITNESS/WORKOUT LOW
                                  TOP, HSCode: 640411
                                  Material Content: Textile (100%
                                  Polyester)/Synthetic Plastic
                                  **********************************
                                  38 CTN // 0.85 CBM // 78.53 KGS
                                  38 Cartons of Footwear Division of goods, Qty:
                                  100 PR
                                  Buy Group: FIRST QUALITY, AFS: 01000
                                  Ship-to Plant: 1084, Customer:
                                  Invoice#: PCVJ2508881
                                  PO-Item: 3503830020-20, Customer PO:
                                  Material: IM8053-237, Name: WMNS NIKE T90 SE,
                                  Gender/Age: WOMENS
                                  Standard Description: WOMENS SOCCER LOW TOP,
                                  HSCode: 640399
                                  Material Content: Full Grain Cow Leather/Textile
                                  (100% Polyester)/OUTSOLE: 100% Rubber
                                  **********************************
                                  (*)
                                  POU CHEN VIETNAM ENTERPRISE LTD.
                                  (**)
                                  Phone: 81-3-4463-6453 / Fax:81-3-4463-6454
                                  E-mail: Lst-JPN.Trade.Customs@nike.com
                                  >
                                  Phone:+81-3-6865-1206
                                  FAX#+81-3-3455-1759
                                  OCM-CTP"
                                  Part Load Container(s) covered by BLs:
                                  ASC0481452
                                  ASC0483157
                                  ASC0483159
                                  ASC0483160
                                  ASC0483091
                                  ASC0483158
                                  ASC0483161
                                  ASC0483162
                                  ASC0483163
                                  ASC0483164
                                  ASC0483165
                                  ASC0483166
                                  ASC0483167
                                  FREIGHT COLLECT
ASC0483158
of
2
Sheet
HO CHI MINH CITY
TOKYO
HO CHI MINH CITY
PRE CARRIAGE BY*
  PLACE OF RECEIPT*
  FREIGHT TO BE PAID AT
VESSEL
  PORT OF LOADING
  FINAL PLACE OF DELIVERY*
  PORT OF DISCHARGE
MARKS AND NOS
CONTAINER AND SEALS
NO AND KIND
OF PACKAGES
DESCRIPTION OF PACKAGES AND GOODS AS STATED BY SHIPPER
GROSS WEIGHT
CARGO
MEASUREMENT
TARE
PLACE AND DATE OF ISSUE
SIGNED FOR THE SHIPPER
*APPLICABLE ONLY WHEN THIS DOCUMENT IS USED AS A COMBINED
TRANSPORT BILL OF LADING
VOYAGE NUMBER
ADDITIONAL CLAUSES
19 OCT 2025
ZERO (0)
TOKYO
SHIPPER'S LOAD  STOW AND COUNT    SAID TO CONTAIN
NON NEGOTIABLE
WAYBILL
WAYBILL NUMBER
NUMBER OF ORIGINAL WAYBILLS
KGS
KGS
CBM
as agents for the carrier CMA CGM Asia Shipping Pte. Ltd.
SIGNED FOR THE CARRIER CMA CGM Asia Shipping Pte. Ltd.
BY
_______________________________________________
CMA CGM VIETNAM JSC
Merchant is reminded that in case of discrepancy between the Verified Gross Mass (VGM) sent to the
Carrier, or the weight declared to the Carrier for non-containerized cargo, and the weight declared by the
Merchant in any shipping instruction or otherwise weighted during the Carriage, the Carrier shall be
entitled to charge the fees referred to in clause 25(5) of the Bill of Lading.
Merchant consents to the Carrier sharing information and data contained in the Bill of Lading and/or
related to the performance of the Carriage of the Goods with third parties, including but not limited to
digital supply chain platforms.
PANAY
3CGIEN1NC
3
Continued From Previous Sheet
                                  PREPAID CHARGES:
                                  COLLECT CHARGES:
                                  BASIC OCEAN FREIGHT: USD 0.03
                                  TERMINAL HANDLING CHARGE (DTHC: JPY 1,666.00
                                  DOCUMENTATION FEE AT ORIGIN: USD 0.00
                                  DOCUMENTATION FEE AT DESTINATI: USD 0.00
                                  83% CO2 REDUCTION: USD 4.08
                                  COMMUNICATION FEE AT ORIGIN: USD 0.00
                                  BUNKER ADJUSTMENT FACTOR: USD 6.43
                                  CONTAINER RETURN FEE AT DESTIN: USD 0.00
ASC0483158
3
of
3
Sheet
HO CHI MINH CITY
TOKYO
HO CHI MINH CITY
PRE CARRIAGE BY*
  PLACE OF RECEIPT*
  FREIGHT TO BE PAID AT
VESSEL
  PORT OF LOADING
  FINAL PLACE OF DELIVERY*
  PORT OF DISCHARGE
MARKS AND NOS
CONTAINER AND SEALS
NO AND KIND
OF PACKAGES
DESCRIPTION OF PACKAGES AND GOODS AS STATED BY SHIPPER
GROSS WEIGHT
CARGO
MEASUREMENT
TARE
PLACE AND DATE OF ISSUE
SIGNED FOR THE SHIPPER
*APPLICABLE ONLY WHEN THIS DOCUMENT IS USED AS A COMBINED
TRANSPORT BILL OF LADING
VOYAGE NUMBER
19 OCT 2025
ZERO (0)
TOKYO
SHIPPER'S LOAD  STOW AND COUNT    SAID TO CONTAIN
NON NEGOTIABLE
WAYBILL
WAYBILL NUMBER
NUMBER OF ORIGINAL WAYBILLS
KGS
KGS
CBM
as agents for the carrier CMA CGM Asia Shipping Pte. Ltd.
SIGNED FOR THE CARRIER CMA CGM Asia Shipping Pte. Ltd.
BY
_______________________________________________
Shipped on Board PANAY 19-OCT-2025 CMA CGM VIETNAM JSC As agents
for the Carrier
      180.130
3700
        2.270
Weight in Kgs Total: 1 CONTAINER(S)
CMA CGM VIETNAM JSC
PANAY
3CGIEN1NC
SHIPPERS DECLARED VALUE
SUBJECT TO EXTRA FREIGHT AS PER TARIFF AND THE CARRIER'S B/L TERMS & CONDITIONS...
----------------------------------------
Processing section: Trading Company  Commercial Invoice
Content snippet: SELLER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
SINGAPORE 117440
SINGAPORE
Company Registration Number: T16FC0027D
GST Registration Number: M90367331L
BUYER:
NIKE JAPAN GROUP LLC
9-7-1 AKASAKA
MIDTOWN TOWER
TOKYO 107-6210
MINATO-KU
JAPAN
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
ICHIKAWA 272-0001
JAPAN
Invoice Number:
4302168583
Invoice Date:
July 30, 2025
Reference Invoice #:
PCVJ2509981
SAP Factory Code:
VP
Terms of Sale:
FOB
Mode of  Transportation:
Vessel
Vessel/Airline:
Ship Date:
August 06, 2025
From:
Ho Chi Minh, Vietnam
To:
Tokyo, Tk Japan
Shipping Marks
Description of Goods
Size Range
Quantity
Unit Price
Amount
31 Cartons of Footwear Division Goods
PR
JPY
1084
To:
Tokyo, Tk Japan
Country of Origin:
Vietnam
Material#:
HV9981-200
Desc: W NIKE FLEX TRAIN
Material Content:
Textile (100%
Polyester)/Synthetic Plastic
Standard Description:
WOMENS
FITNESS/WORKOUT LOW TOP
Gender/Age:
WOMENS
Line:
WOMENS TRAINING
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
                                Plant:
1084
AFS Category: 01000
Buy Group:
FIRST QUALITY
PO#:
3503842282
Reference PO#:
8501935073
PO Line Item Seq.#:
00090
Sizes:
5-11
       68
3,201
217,668
--------------------------------------------------------------------------------------------------------------------------------------------------------
Total Number of
Cartons:
31
Total Invoice
Quantity:
68 Total Amount:
217,668
Total Gross Weight:
52.49 Kgs
Total Net Weight:
28.73 Kgs
Manufacturing Factory:
POU CHEN VIETNAM ENTERPRISE LTD.
Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province, Vietnam
Page 1 of    2
Printed on:
2025/08/04
19:41:25
INV#
Style#
PO#
PO line#
Total quantity
Total Weight
total carton
Trading Company  Commercial Invoice
(continued)
SELLER :
NIKE Global Trading BV Singapore Branch
SINGAPORE 117440
SHIP TO:
Nike Japan MN-Ichikawa
Invoice Number:
4302168583
Invoice Date:
July 30, 2025
Page 2 of    2
Printed on:
2025/08/04
19:41:25
PCVJ2509981
July 30, 2025
VP
FOB
XXXXVP
Invoice Number:
Mode of Transportation:
Invoice Date:
SAP Factory Code:
Terms of Sale:
L/C or OA Ref#:
Vessel/Airline:
From:...
----------------------------------------
Processing section: Factory Commercial Invoice
Content snippet: Ho Chi Minh, Vietnam
Vessel
SELLER:
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan
BUYER:
NIKE Global Trading BV Singapore Branch
30 Pasir Panjang Road
#10-31/32 Mapletree Business City
Singapore  117440
SINGAPORE
SHIP TO:
Nike Japan MN-Ichikawa
ACCA International-Digital/NSO
ESR ICHIKAWA Distribution Center 1F
678-55 Futamata
Ichikawa, CH  272-0001
Japan
August 6, 2025
Ship Date:
Reference Invoice #:
Tokyo, Tk Japan
To:
4302168583
Shipping Marks
Description of Goods
Size
Range
Amount
Unit Price
Quantity
PR
USD
31
Cartons of Footwear Division Goods
HV9981-200
Material #:
Desc.:
W NIKE FLEX TRAIN
Material Content: Textile (100%
Polyester)/Synthetic Plastic
Standard Description: WOMENS
FITNESS/WORKOUT LOW TOP
Line:
Purchase Doc Date:
20250521
HO2025
Ship To ID#:
Plant: 1084
AFS Category:
01000
Buy Group:
Country Of Origin:
Vietnam
WOMENS TRAINING
Gender/Age:
WOMENS
PO#:
FIRST QUALITY
8501935073
Sizes:
00090
PO Line Item Seq. #:
Reference PO#:
3503842282
Booking Number: VB25072607136389
1084
Tokyo, Tk Japan
5 - 11
 68
 18.67
 1,269.56
 68
Total Invoice Quantity:
Total Amount:
 1,269.56
Total Number of Cartons:
 31
 28.73
 52.49
Total Gross Weight:
Total Net Weight:
Kgs
Kgs
Page 1 of 2
Aug-5-2025
 2:29:37PM
Printed on:
INV#
Style#
PO#
PO line#
Total quantity
Total Weight
total carton
SELLER:
SHIP TO:
PCVJ2509981
July 30, 2025
Invoice Number:
Invoice Date:
Factory Commercial Invoice (Continued)
Yue Yuen Industrial Limited, Taiwan Branch
Nike Japan MN-Ichikawa
Shipping Marks
Description of Goods
Size
Range
Amount
Unit Price
Quantity
PR
USD
Manufacturing Factory:
POU CHEN VIETNAM ENTERPRISE LTD.
Nguyen Ai Quoc Street, An Hoa Quarter,
Bien Hoa Ward, Dong Nai Province, Vietnam
Page 2 of 2
Aug-5-2025
 2:29:37PM
Printed on:
seller:
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan...
----------------------------------------
Processing section: Factory Packing List
Content snippet: 1084
Date:
July 30, 2025
PO# :
Factory Code:
AFS Category:
Material:
Plant:
Item Seq.:
Customer Ship To: #:
Customer SO-Line #:
Customer PO #:
HV9981-200
1084
Purchase Doc Date:
MSR:
Total Gross Kgs:
Total CBM:
Total Cartons:
Total Units:
 31
 68
VP
01000
Invoice Number.:
20250521
HO2025
 0.73
00090
To:
Total Net Kgs:
 52.49
 28.73
Lot Numbers:
G2505B02127
No
Manufacturer ID:
009120196
Buy Group:
FIRST QUALITY
Tokyo, Tk Japan
PCVJ2509981
Reference PO#:
8501935073
3503842282
VB25072607136389
Booking Number:
Desc:
W NIKE FLEX TRAIN
Tokyo, Tk Japan
Vietnam
Country Of Origin:
From
To
Type
5
5.5
6
6.5
7
7.5
8
8.5
9
10
10.5
11
 Units
Cartons
Carton Range
Number of
Ctn.
Carton Contents -- Quantity by Size
4334956 4334957
 2
S1
2
 1
4334958 4334958
 1
S1
1
 1
4334959 4334959
 6
XM3
1
 6
4334961 4334961
 6
XM3
1
 6
4334963 4334964
 12
XM3
2
 6
4334966 4334967
 12
XM3
2
 6
4334968 4334968
 6
XM3
1
 6
4334969 4334969
 1
S1
1
 1
4334970 4334972
 3
S1
3
 1
4334973 4334973
 1
S2
1
 1
4334974 4334974
 1
S2
1
 1
4334975 4334975
 2
S3
1
 2
Page 1 of 2
 2:29:38PM
Aug -5-2025
Printed on:
total weight
INV#
PO#
PO line#
Style#
seller:
(Continued)
Yue Yuen Industrial Limited, Taiwan Branch
No. 2, Fugong Rd., Fuxing Township,
Changhua County, 50662, Taiwan
Factory Packing List
1084
Date:
July 30, 2025
PO# :
Factory Code:
AFS Category:
Material:
Plant:
Item Seq.:
Customer Ship To: #:
Customer SO-Line #:
Customer PO #:
HV9981-200
1084
Purchase Doc Date:
MSR:
Total Gross Kgs:
Total CBM:
Total Cartons:
Total Units:
 31
 68
VP
01000
Invoice Number.:
20250521
HO2025
 0.73
00090
To:
Total Net Kgs:
 52.49
 28.73
Lot Numbers:
G2505B02127
No
Manufacturer ID:
009120196
Buy Group:
FIRST QUALITY
Tokyo, Tk Japan
PCVJ2509981
Reference PO#:
8501935073
3503842282
VB25072607136389
Booking Number:
Desc:
W NIKE FLEX TRAIN
Tokyo, Tk Japan
Vietnam
Country Of Origin:
From
To
Type
5
5.5
6
6.5
7
7.5
8
8.5
9
10
10.5
11
 Units
Cartons
Carton Range
Number of
Ctn.
Carton Contents -- Quantity by Size
4334976 4334976
 2
S3
1
 2
4334977 4334977
 1
S2
1
 1
4334978 4334980
 3
S1
3
 1
4334981 4334984
 4
S1
4
 1
4334985 4334989
 5
S1
5
 1
Total:
 68
31
3
2
1
1
3
7
12
17
10
9
1
2
Page 2 of 2
 2:29:38PM
Aug -5-2025
Printed on:...
----------------------------------------
Processing section: MULTIPLE COUNTRY OF ORIGIN DECLARATION
Content snippet: We are  POU CHEN VIETNAM ENTERPRISE LTD - declare that the articles described below and coverd by the invoice or entry to which declaration relates were exported from the country
" identified below on the dates listed and were subjected to assembling , manufacturing or processing operations in , and/or incorporate materials originating in the
foreign territory of country", or the U.S. or an insular prossession of the U.S. identified below . I declare that the information set forth in this declaration is correct
and true to the best of my information , knowledge, and belidf .
A __TAIWAN--------------__(Country")
C_KOREA_____________________________(Country")
B __VIETNAM___(Country")
D__________________________________(Country")
Description of
Description of country of manufacturing
Materials
article and quantity
manufacturing
and or processing
and or processing
operations
Country
Date of
Description
Country
Date of
exportation
of materials
of origin
exportation

INVOICE NO.
PCVJ2509981
Making
B
08/06/25
A
06/07/25
31 CNTS OF NIKE FOOTWEAR GOODS
cutting
CAT
sewing
MATERIAL
HV9981-200
ITEM : 90
lasting
DESC.



GENDER
WOMENS
MATERIAL CONTENT 34% Plastic & 66% Textile
PURCHASE DOC DATE 20250521
SHIP TO ID#
PLANT
1084
AFS CATEGORY
01000
P.O. #:
3503842282
BUY GROUP
01
DATE  :
08/02/2025
NAME :
SIGNATURE :

In [9]:
df

,Bill Name,Invoice#:,PO-Item:,Material:,NO MARKS,Reference Invoice #:,Material#:,Material #:,Invoice Number:,Total Gross Weight:,Reference PO#:,Total Number of Cartons:,Total Invoice Quantity:,PO Line Item Seq. #:,Invoice Number.:,INVOICE NO. \n :,STYLE/CLR:
0,WAYBILL,PCVJ2508881,"3503830020-20, Customer PO:","HV9981-600, Name: W NIKE FLEX TRAIN,",⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found
1,Trading Company Commercial Invoice,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,PCVJ2509981,HV9981-200,⚠️ Not Found,4302168583,52.49 Kgs,8501935073,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found
2,Factory Commercial Invoice,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,"Tokyo, Tk Japan",⚠️ Not Found,Desc.:,Invoice Date:,Total Net Weight:,3503842282,⚠️ Not Found,Total Amount:,Reference PO#:,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found
3,Factory Packing List,⚠️ Not Found,⚠️ Not Found,Plant:,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,8501935073,⚠️ Not Found,⚠️ Not Found,⚠️ Not Found,20250521,⚠️ Not Found,⚠️ Not Found
4,MULTIPLE COUNTRY OF ORIGIN DECLARATION,⚠️ Not Found,⚠️ Not Found,Plant:,⚠️ Not Found,PCVJ2509987,HV9981-600,Desc.:,4302168585,49.11 Kgs,8501935073,⚠️ Not Found,Total Amount:,Reference PO#:,20250521,⚠️ Not Found,⚠️ Not Found